# Site settings
title: IIFRP.org
email:
description: >
  Improving and standardizing the design, development, and construction of food.
baseurl: ""
url: "https://iifrp.org"
twitter_username: iifrporg
github_username:  iifrp

# Build settings
markdown: kramdown

permalink: /document/:title:output_ext

collections:
    rfc:
        output: true

plugins_dir:
  - jekyll-archives
  - jekyll-feed
  - jekyll-sitemap
